# Generated by Django 6.0.6 on 2026-06-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0002_remove_service_category_remove_service_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphoto',
            name='project',
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('status', models.CharField(choices=[('working', 'Работает'), ('repair', 'На ремонте'), ('decommissioned', 'Списано')], default='working', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Местонахождение')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_app.department', verbose_name='Подразделение')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_app.employee', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_app.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
    ]
