# Generated by Django 6.0.6 on 2026-06-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0003_remove_projectphoto_project_equipment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cabinet',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='staff',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во сотрудников'),
        ),
    ]
