# Generated by Django 6.0.6 on 2026-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0004_employee_cabinet_worktype_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Должность')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('slots', models.PositiveIntegerField(default=0, verbose_name='Вакантных мест')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['title'],
            },
        ),
    ]
