# Generated by Django 6.0.6 on 2026-06-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0005_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_app.department', verbose_name='Вышестоящее подразделение'),
        ),
    ]
