# Generated by Django 6.0.6 on 2026-06-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0006_department_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='s_app.equipment', verbose_name='Оборудование'),
        ),
    ]
